#1
name: Flutter - IOS Build

#2
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

#3
jobs:
  buid:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup env file
        run: |
          mkdir -p lib/config/env
          echo "${{ secrets.ENV_FILE }}" | base64 --decode > lib/config/env/.env
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.4

      - name: Install dependencies
        run: flutter pub get

      - name: Install iOS dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA
        run: flutter build ios --release --build-name=1.0.0 --build-number=1 --no-codesign